export { default as Home } from './Home'
export { default as Services } from './Services'
export { default as Gallery } from './Gallery'
export { default as AboutUs } from './AboutUs'
export { default as ContactUs } from './ContactUs'
export { default as DetailedService } from './DetailedService'